###########################################################
#                      GLOBAL SETTING                     #
###########################################################
seed: 1
n_class: 24
n_fold: 5
###########################################################
#                    PREPROCESS SETTING                   #
###########################################################
sr: 48000
fft_size: 2048
hop_size: 512
window: hann
num_mels: 128
fmin: 50
fmax: 16000
###########################################################
#                     NETWORK SETTING                     #
###########################################################
model_type: "Cnn14_DecisionLevelAtt" # pretrained model's type.
att_block:
  n_in: 2048
  n_out: 24
  activation: sigmoid

model_params:
  sample_rate: 16000
  window_size: 1024
  hop_size: 256
  mel_bins: 64
  fmin: 50
  fmax: 8000
  classes_num: 527
  require_prep: False
  is_spec_augmenter: True
###########################################################
#                    TRAINING SETTING                     #
###########################################################
# dataset
train_dataset_mode: tp
allow_cache: True # Whether to allow cache in dataset. If true, it requires cpu memory.
is_normalize: False
# collater_fc
max_frames: 512
l_target: 16
collater_mode: binary
# dataloader
accum_grads: 2
batch_size: 32 # Batch size.
pin_memory: False # Whether to pin memory in Pytorch DataLoader.
num_workers: 2 # Number of workers in Pytorch DataLoader.
# trainer
use_center_loss: False
###########################################################
#                       LOSS SETTING                      #
###########################################################
loss_type: BCEWithLogitsLoss
loss_params:
  reduction: mean

###########################################################
#              OPTIMIZER & SCHEDULER SETTING              #
###########################################################
optimizer_type: "Adam"
optimizer_params:
  conv_lr: 0.0001 # convolution layer's learning rate.
  fc_lr: 0.001 # full connection layer's learning rate.
scheduler_type: "StepLR"
scheduler_params:
  step_size: 1000 # scheduler step size.
  gamma:
    0.5 # scheduler gamma.
    # At each step size, lr will be multiplied by this parameter.
###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 2000 # Number of training steps.
save_interval_steps: 1000 # Interval steps to save checkpoint.
eval_interval_epochs: 2 # Interval epochs to evaluate the network.
###########################################################
#                     OTHER SETTING                       #
###########################################################
n_eval_split: 20
